SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    (SUM(bs.SALES * b.PRICE)) AS TOTAL_SALES
FROM
    BOOK_SALES AS bs
JOIN
    BOOK AS b
ON
    bs.BOOK_ID = b.BOOK_ID
JOIN
    AUTHOR as a
ON
    a.AUTHOR_ID = b.AUTHOR_ID
WHERE
    YEAR(SALES_DATE) = '2022'
    AND
    MONTH(SALES_DATE) = '1'
GROUP BY
    b.AUTHOR_ID, b.CATEGORY
ORDER BY
    b.AUTHOR_ID, b.CATEGORY DESC