SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK AS A
JOIN AUTHOR AS B
    USING (AUTHOR_ID)
JOIN BOOK_SALES AS C
    USING (BOOK_ID)
WHERE
    YEAR(C.SALES_DATE) = '2022'
        AND
    MONTH(C.SALES_DATE) = '1'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC