WITH MILK AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)
, YOGURT AS (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)

SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE
    CART_ID IN (SELECT * FROM MILK)
    AND
    CART_ID IN (SELECT * FROM YOGURT)
ORDER BY CART_ID