WITH RECURSIVE GENERATION AS(
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT A.ID, A.PARENT_ID, B.GEN + 1 AS GEN
    FROM ECOLI_DATA AS A
    JOIN GENERATION B
        ON A.PARENT_ID = B.ID
)

SELECT ID
FROM GENERATION
WHERE GEN = '3'
ORDER BY ID