WITH UU AS (
    SELECT PARENT_ITEM_ID AS ITEM_ID
    FROM ITEM_TREE
    WHERE
        PARENT_ITEM_ID IS NOT NULL
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE
    ITEM_ID NOT IN (SELECT ITEM_ID FROM UU)
ORDER BY ITEM_ID DESC