WITH CC AS (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE
        PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID)

SELECT A.ID, IFNULL(CC.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS A
LEFT JOIN CC
    ON A.ID = CC.PARENT_ID