WITH CB AS (
    SELECT DISTINCT CAR_ID, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    JOIN CAR_RENTAL_COMPANY_CAR
        USING (CAR_ID)
    WHERE
        CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
)
, CAR AS (
    SELECT DISTINCT CAR_ID, B.CAR_TYPE, B.DAILY_FEE
    FROM CB AS A
    JOIN CAR_RENTAL_COMPANY_CAR AS B
        USING (CAR_ID)
    WHERE
        B.CAR_TYPE IN ('SUV', '세단')
)
, T AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE
        DURATION_TYPE = '30일 이상'
)

, F AS (
    SELECT CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100)) * 30 AS FEE
    FROM CAR AS A
    JOIN T AS B
        USING (CAR_TYPE)
)

SELECT *
FROM F
WHERE
    FEE >= 500000
    AND
    FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
