SELECT ID, 
    CASE
        WHEN NR = '1' THEN 'CRITICAL'
        WHEN NR = '2' THEN 'HIGH'
        WHEN NR = '3' THEN 'MEDIUM'
        WHEN NR = '4' THEN 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, NTILE(4) OVER (
            ORDER BY SIZE_OF_COLONY DESC) AS NR
    FROM ECOLI_DATA) AS t
ORDER BY ID;