WITH LANKING AS (
    SELECT NTILE(4)
        OVER (ORDER BY SIZE_OF_COLONY DESC)
        AS LANK, ID
    FROM ECOLI_DATA)

SELECT ID,
    (CASE
        WHEN LANK = 1 THEN 'CRITICAL'
        WHEN LANK = 2 THEN 'HIGH'
        WHEN LANK = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END
    ) AS COLONY_NAME
FROM LANKING
ORDER BY ID