WITH I AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE
        SEX_UPON_INTAKE LIKE "Intact%"
)
, S AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE
        SEX_UPON_OUTCOME LIKE "Spayed%"
        OR
        SEX_UPON_OUTCOME LIKE "Neutered%"
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE
    ANIMAL_ID IN (SELECT * FROM I)
    AND
    ANIMAL_ID IN (SELECT * FROM S)
ORDER BY ANIMAL_ID