WITH REVIEW_SCORE AS (
    SELECT ROUND(AVG(REVIEW_SCORE), 2) AS SCORE, REST_ID
    FROM REST_REVIEW
    GROUP BY REST_ID)

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE
FROM REST_INFO AS A
JOIN REVIEW_SCORE AS B
    USING (REST_ID)
WHERE
    A.ADDRESS LIKE '서울%시%'
ORDER BY B.SCORE DESC, A.FAVORITES DESC