SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A
RIGHT OUTER JOIN REST_REVIEW AS B
    ON B.REST_ID = A.REST_ID
WHERE
    A.ADDRESS LIKE '서울%시%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC