WITH CR AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        '2022-10-16' BETWEEN DATE(START_DATE) AND DATE(END_DATE)
    )
, CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, 
    CASE
        WHEN CAR_ID IN (SELECT CAR_ID
                       FROM CR)
                       THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CARS
ORDER BY CAR_ID DESC