WITH FO AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TS
    FROM FOOD_ORDER
    WHERE
        YEAR(PRODUCE_DATE) = '2022'
        AND
        MONTH(PRODUCE_DATE) = '5'
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_ID, B.PRODUCT_NAME, (B.PRICE * A.TS) AS TOTAL_SALES
FROM FO AS A
JOIN FOOD_PRODUCT AS B
    USING (PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID