WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM TIME
    WHERE HOUR < 23
)

SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM TIME AS A
LEFT JOIN 
    (SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR
     FROM ANIMAL_OUTS) AS B
    ON A.HOUR = B.HOUR
GROUP BY HOUR
ORDER BY HOUR