WITH TIME AS (
    SELECT TIME_FORMAT(DATETIME, '%H') AS HOUR
    FROM ANIMAL_OUTS
    WHERE
        TIME_FORMAT(DATETIME, '%H')
        BETWEEN 09 AND 19
    )

SELECT HOUR, COUNT(*) AS COUNT
FROM TIME
GROUP BY HOUR
ORDER BY HOUR