WITH MC AS (
    SELECT COUNT(*) AS CNT, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
, MR AS (
    SELECT CNT, MEMBER_ID
    FROM MC
    WHERE
        CNT = (
            SELECT MAX(CNT)
            FROM MC)
    LIMIT 1
)

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS A
JOIN MEMBER_PROFILE AS B
    USING (MEMBER_ID)
WHERE
    MEMBER_ID = (
        SELECT MEMBER_ID
        FROM MR)
ORDER BY REVIEW_DATE, REVIEW_TEXT