WITH TIME AS (
    SELECT *
    FROM APPOINTMENT
    WHERE
        YEAR(APNT_YMD) = '2022'
        AND
        MONTH(APNT_YMD) = '5'
    )

SELECT MCDP_CD AS '진료과코드', COUNT(*) AS '5월예약건수'
FROM TIME
GROUP BY MCDP_CD
ORDER BY COUNT(*), MCDP_CD