WITH CR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        DATE(START_DATE) BETWEEN '2022-08-01' AND '2022-10-31'
    )
, RENTAL_COUNT AS (
    SELECT CAR_ID, COUNT(*) AS RECORDS
    FROM CR
    GROUP BY CAR_ID
    )
, MORE_THAN_FIVE AS (
    SELECT CAR_ID
    FROM RENTAL_COUNT
    WHERE
        RECORDS >= 5
    )

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CR
WHERE
    CAR_ID IN (
        SELECT *
        FROM MORE_THAN_FIVE)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE), CAR_ID DESC