SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (B.MAXSIZE - SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
LEFT JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA AS A
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS B
    ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV