SELECT A.FLAVOR
FROM ICECREAM_INFO AS A
JOIN (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF
    WHERE TOTAL_ORDER > 3000) AS B
    USING (FLAVOR)
WHERE
    A.INGREDIENT_TYPE = 'fruit_based'
ORDER BY B.TOTAL_ORDER DESC;