SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    USING (CAR_ID)
WHERE
    A.CAR_TYPE = '세단'
    AND
    MONTH(B.START_DATE) = '10'
ORDER BY CAR_ID DESC