WITH SCORES AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO)
    
, MAX_SCORE AS (
    SELECT EMP_NO, SCORE
    FROM SCORES
    WHERE
        SCORE = (SELECT MAX(SCORE)
                FROM SCORES))

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS A
JOIN SCORES AS B
    USING (EMP_NO)
WHERE
    EMP_NO = (SELECT EMP_NO
             FROM MAX_SCORE)