WITH TOTAL AS (
    SELECT A.FLAVOR, A.INGREDIENT_TYPE, B.TOTAL_ORDER
    FROM ICECREAM_INFO AS A
    JOIN FIRST_HALF AS B
    USING (FLAVOR))

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM TOTAL
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER