WITH SAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID)

SELECT A.DEPT_ID, B.DEPT_NAME_EN, A.AVG_SAL
FROM SAL AS A
JOIN HR_DEPARTMENT AS B
    USING(DEPT_ID)
ORDER BY A.AVG_SAL DESC