WITH MV AS (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
, BI AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE
        VIEWS = (SELECT * FROM MV)
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
WHERE
    BOARD_ID = (SELECT * FROM BI)
ORDER BY FILE_ID DESC