WITH TOTAL AS (
    SELECT A.SALES, B.CATEGORY
    FROM BOOK_SALES AS A
    JOIN BOOK AS B
        USING (BOOK_ID)
    WHERE
        YEAR(SALES_DATE) = '2022'
        AND
        MONTH(SALES_DATE) = '1')

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM TOTAL
GROUP BY CATEGORY
ORDER BY CATEGORY