WITH MP AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT B.CATEGORY, A.MAX_PRICE, B.PRODUCT_NAME
FROM MP AS A
JOIN FOOD_PRODUCT AS B
    ON A.MAX_PRICE = B.PRICE AND A.CATEGORY = B.CATEGORY
ORDER BY MAX_PRICE DESC