WITH FI AS (
    SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH, TIME
    FROM FISH_INFO
)

, AVGS AS (
    SELECT FISH_TYPE, AVG(LENGTH) AS LENGTH
    FROM FI
    GROUP BY FISH_TYPE)

, MAX_FISH AS(
    SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
    FROM FI
    GROUP BY FISH_TYPE
)

SELECT *
FROM MAX_FISH
WHERE
    FISH_TYPE IN
        (SELECT FISH_TYPE
        FROM AVGS
        WHERE LENGTH >= 33)
ORDER BY FISH_TYPE